name: maintenance

on: push

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format-18 -style=file -i

    - name: generate
      run: python ${{ github.workspace }}/res/scripts/generate_headers.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: maintenance
